#!/usr/bin/env bash
# export-main.sh — orchestrator: publish per-framework flat-root DISTRIBUTION branches + tags.
#
# Maintainer tool. Runs from anywhere in the repo. NEVER merges.
#
# `main` is the SOURCE TRUNK and is NOT regenerated by this script. This script
# publishes the DISTRIBUTION branches — `angular` and `react` — each a fresh,
# self-contained, single-commit ORPHAN whose ROOT holds:
#   shared root payload (STANDARD.md, infra/cognito/) + that framework's payload.
# The flat-root layout is what makes `npm i git+…#angular` / `npx git+…#react`
# resolvable: a git dependency installs the repo ROOT of a ref, and npm has no
# "install this subdirectory" for git deps. One framework per ref → root package.
#
# Layout produced on each distribution branch (example: angular):
#   README.md      (packages/angular/README-main.md — framework-specific, overwrites the shared one)
#   STANDARD.md    (shared)
#   infra/cognito/ (shared)
#   package.json, schematics/   (Angular payload, at ROOT)
# React ships copy-in source (src/) at root; its npx CLI is bundled in a later work unit.
#
# Usage: export-main.sh [--version X.Y.Z] [--only angular|react]
#   --version  stamp each framework's package.json (if present) and cut tag <fw>-vX.Y.Z
#   --only     publish a single framework (default: both)
#
# SAFETY INVARIANT: the ONLY mutations to real refs are
#   `git branch -f angular` / `git branch -f react`  (+ optional `git tag -f <fw>-vX.Y.Z`).
# `main` is never touched. Everything else happens in disposable worktrees/stage
# dirs under $TMPDIR — the caller's working tree is never modified.
set -euo pipefail

VERSION=""
ONLY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) VERSION="${2:?--version needs a value}"; shift 2 ;;
    --only)    ONLY="${2:?--only needs a value (angular|react)}"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

REPO_ROOT="$(git rev-parse --show-toplevel)"
ROOT_MANIFEST="$REPO_ROOT/scripts/curated-manifest-root.txt"
[[ -f "$ROOT_MANIFEST" ]] || { echo "ERROR: root manifest not found: $ROOT_MANIFEST" >&2; exit 1; }

# Which frameworks to publish.
FRAMEWORKS=(angular react)
if [[ -n "$ONLY" ]]; then
  case "$ONLY" in
    angular|react) FRAMEWORKS=("$ONLY") ;;
    *) echo "ERROR: --only must be 'angular' or 'react' (got '$ONLY')" >&2; exit 2 ;;
  esac
fi

# Refuse to force-move a distribution branch that is currently checked out:
# `git branch -f <fw>` fails with a cryptic fatal in that case.
CUR_BRANCH="$(git -C "$REPO_ROOT" symbolic-ref --quiet --short HEAD || true)"
for fw in "${FRAMEWORKS[@]}"; do
  if [ "$CUR_BRANCH" = "$fw" ]; then
    echo "ERROR: refuse to regenerate '$fw' while it is checked out. Switch to your working/source branch first." >&2
    exit 1
  fi
done

# --- cleanup state (arrays; trap tears everything down on ANY exit) -------------
# One entry per published framework — accumulated as we go so a mid-run death
# still cleans every scratch artifact created up to that point.
declare -a STAGES=() WORKTREES=() WT_PARENTS=() TMP_BRANCHES=()
cleanup() {
  local i
  for i in "${!WORKTREES[@]}"; do
    local wt="${WORKTREES[$i]}"
    [[ -n "$wt" && -e "$wt" ]] && { git -C "$REPO_ROOT" worktree remove --force "$wt" 2>/dev/null || rm -rf "$wt"; }
  done
  for wp in "${WT_PARENTS[@]}"; do [[ -n "$wp" && -d "$wp" ]] && rm -rf "$wp"; done
  for tb in "${TMP_BRANCHES[@]}"; do
    [[ -n "$tb" ]] && git -C "$REPO_ROOT" rev-parse -q --verify "refs/heads/$tb" >/dev/null 2>&1 \
      && git -C "$REPO_ROOT" branch -D "$tb" >/dev/null 2>&1 || true
  done
  for st in "${STAGES[@]}"; do [[ -n "$st" && -d "$st" ]] && rm -rf "$st"; done
  git -C "$REPO_ROOT" worktree prune 2>/dev/null || true
}
trap cleanup EXIT

# --- helper: stage a manifest into a target dir ---------------------------------
stage_manifest() {
  local manifest="$1" target="$2"
  while IFS= read -r raw || [[ -n "$raw" ]]; do
    line="${raw%%#*}"; line="$(printf '%s' "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [[ -z "$line" ]] && continue
    src="$(printf '%s' "${line%%->*}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    dst="$(printf '%s' "${line#*->}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [[ -z "$src" || -z "$dst" || "$src" == "$line" ]] && { echo "ERROR: malformed manifest line: $raw" >&2; exit 1; }
    abs_src="$REPO_ROOT/$src"
    [[ -e "$abs_src" ]] || { echo "ERROR: manifest source not found: $src" >&2; exit 1; }
    mkdir -p "$(dirname "$target/$dst")"
    cp -R "$abs_src" "$target/$dst"
  done < "$manifest"
}

# --- publish ONE framework as a fresh flat-root orphan branch (+ optional tag) ---
publish_framework() {
  local fw="$1"

  # 1. Shared root payload. NOTE: this stages the monorepo README.md, which the
  #    framework's own export.sh overwrites in step 2 (framework README wins —
  #    each distribution branch is a self-contained, framework-specific home).
  local STAGE; STAGE="$(mktemp -d)"; STAGES+=("$STAGE")
  echo "[$fw] staging shared root payload..."
  stage_manifest "$ROOT_MANIFEST" "$STAGE"

  # 2. Framework payload — staged at the STAGE ROOT (export.sh writes relative to
  #    its target dir), giving the flat-root layout npm/npx needs.
  echo "[$fw] staging $fw payload at root..."
  bash "$REPO_ROOT/packages/$fw/scripts/export.sh" "$STAGE"

  # 3. Version-stamp this framework's package.json, if it has one and --version given.
  if [[ -n "$VERSION" ]]; then
    if [[ -f "$STAGE/package.json" ]]; then
      node -e '
        const fs = require("fs");
        const p = process.argv[1], v = process.argv[2];
        const j = JSON.parse(fs.readFileSync(p, "utf8"));
        j.version = v;
        fs.writeFileSync(p, JSON.stringify(j, null, 2) + "\n");
      ' "$STAGE/package.json" "$VERSION"
      echo "[$fw] stamped package.json version=$VERSION"
    else
      echo "[$fw] no package.json to stamp (copy-in payload) — tagging only"
    fi
  fi

  # 4. Build a fresh single-commit orphan via a throwaway worktree, then point the
  #    distribution branch (and optional tag) at it.
  local WT_PARENT WORKTREE TMP_BRANCH NEW_SHA
  WT_PARENT="$(mktemp -d)"; WT_PARENTS+=("$WT_PARENT")
  WORKTREE="$WT_PARENT/wt";  WORKTREES+=("$WORKTREE")
  TMP_BRANCH="export-${fw}-tmp-$$"; TMP_BRANCHES+=("$TMP_BRANCH")

  git -C "$REPO_ROOT" worktree add -q --no-checkout "$WORKTREE" HEAD
  git -C "$WORKTREE" checkout -q --orphan "$TMP_BRANCH"
  git -C "$WORKTREE" rm -rfq --cached . 2>/dev/null || true
  find "$WORKTREE" -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
  cp -R "$STAGE"/. "$WORKTREE"/
  git -C "$WORKTREE" add -A
  git -C "$WORKTREE" -c user.name="s4-auth-export" -c user.email="export@s4-auth.local" \
    commit -q -m "release($fw): s4-auth-${fw} ${VERSION:-unversioned}"
  NEW_SHA="$(git -C "$WORKTREE" rev-parse HEAD)"

  # ONLY real-ref mutations in this script:
  git -C "$REPO_ROOT" branch -f "$fw" "$NEW_SHA"
  if [[ -n "$VERSION" ]]; then
    git -C "$REPO_ROOT" tag -f "${fw}-v${VERSION}" "$NEW_SHA" >/dev/null
    echo "[$fw] published branch '$fw' + tag '${fw}-v${VERSION}' @ ${NEW_SHA:0:12}"
  else
    echo "[$fw] published branch '$fw' @ ${NEW_SHA:0:12} (no tag — pass --version to cut one)"
  fi
}

for fw in "${FRAMEWORKS[@]}"; do
  publish_framework "$fw"
done

echo ""
echo "Done. Distribution branches updated: ${FRAMEWORKS[*]}"
echo "Push branches:  git push --force-with-lease <remote> ${FRAMEWORKS[*]}"
[[ -n "$VERSION" ]] && echo "Push tags:      git push <remote> $(printf '%s-v'"$VERSION"' ' "${FRAMEWORKS[@]}")"
